language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/./mvnw compile'

before_install:
  - chmod +x mvnw

notifications:
  email:
    recipients:
      - llmm030506@gmail.com